import use from './use-selector-observer'
// import use from './use-regular-elements'
import on, { fire, off } from './on-delegated'
// import on, { fire } from './on-delegate-it'
import { run } from './core'
import fx from './fx'
import $ from './$'
import attr from './attr'
import state from './state'
import cls from './class'
import prop from './prop'
import local from './local'
import data from './data'
import query from './query'
import html, { render } from './html-preact'
// import html from './html-idom'
// import html from './html-nanomorph'

export { attr, local, data, query, use, on, off, fire, state, run, fx, prop, $, html, render, cls }
